# Release drafter configuration https://github.com/release-drafter/release-drafter#configuration
# Emojis were chosen to match the https://gitmoji.carloscuesta.me/

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: ":rocket: Features"
    labels: [enhancement, feature]
  - title: ":wrench: Fixes & Refactoring"
    labels: [bug, refactoring, bugfix, fix]
  - title: ":package: Build System & CI/CD"
    labels: [build, ci, testing]
  - title: ":boom: Breaking Changes"
    labels: [breaking]
  - title: ":pencil: Documentation"
    labels: [documentation]
  - title: ":arrow_up: Dependencies updates"
    labels: [dependencies]

template: |
  ## :memo: What’s Changed

  $CHANGES

  ## :busts_in_silhouette: List of contributors

  $CONTRIBUTORS

  ## :motor_boat: Docker Images

  Available on Docker Hub:
  https://hub.docker.com/r/pglombardo/pwpush

  ## :running_man: Run This Version

  ```bash
  docker run -d -p 5100:5100 pglombardo/pwpush:$NEXT_PATCH_VERSION
  ```

  ..and go to `http://localhost:5100`

  ## :link: Useful Links

  * [Documentation](https://docs.pwpush.com)
  * [Docker Hub](https://hub.docker.com/r/pglombardo/pwpush)
  * [GitHub](https://github.com/pglombardo/PasswordPusher)
  * [Website](https://pwpush.com)
  * [Twitter](https://twitter.com/pwpush)
  * [Newsletter](https://buttondown.email/pwpush)
