language: ruby

cache:
  bundler: true
  directories:
    - vendor/bundle

#bundler_args: --without production

rvm:
  - 2.5.1

before_install:
  - gem update --system
  - gem update bundler
  - gem --version

before_script: "bundle exec rake db:migrate RAILS_ENV=test"

script: "bundle exec rake test"
