# Global Application Defaults

# This is initially for internal settings.  If all goes well using
# this new config gem, then we'll migrate entirely to the new Settings
# format for private instances too.

# Logins are not yet supported in private instances due to a bit more support needed.
#   e.g. how to hook up an email MTA.  Coming soon.
enable_logins: false

# The domain (without protocol) where this instance is hosted
# Used in generating fully qualified URLs.
# host_domain: 'pwpush.com'

# The protocol to reach the domain above
# Used in generating fully qualified URLs.
# host_protocol: 'https'

mail:
  raise_delivery_errors: false
  # smtp_address: smtp.example.com
  # smtp_port: 587
  # smtp_user_name: 'apikey'
  # smtp_password: ''
  # smtp_authentication: 'plain'
  # smtp_starttls: true
  # smtp_open_timeout: 10
  # smtp_read_timeout: 10
